# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.1.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"	

# Do not build on tags (GitHub only)
skip_tags: true

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
  files:
    - docs/*
    - '**/*.md'

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several configurations to build matrix:
configuration:
  - Release
  

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run tests from different categories as separate jobs in parallel
test:
  categories:
    - Unit

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: DigiRazor.PasswordService\bin\Release\PasswordValidation.dll
    name: PasswordValidation.dll
  - path: '**\*.nupkg'

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: n/2gZwCGLcoLBr5nGu5akS0IFQ1YHciI6Wz0NGC+1mLTUtO08Uy+TWn7OtyLG9v3
#  artifact: /.*\.nupkg/	