# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

environment:
  my_variable:
    secure: s/cX2qtXI5mnjXc2KJTxcfa6ppLiR+0rD55eiI3Z3SYmS5ZzqWJiXGajDAn2vuo6
    
# version format
version: 0.1.1.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"	

image: Visual Studio 2017

install: 
- cmd: curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe 
- cmd: dotnet-sdk-2.0.0-win-x64.exe /install /quiet /norestart /log install.log    

# Do not build on tags (GitHub only)
skip_tags: false

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
  files:
    - docs/*
    - '**/*.md'

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several configurations to build matrix:
configuration:
  - Release

before_build:
  - nuget restore

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run tests from different categories as separate jobs in parallel
test:
  categories:
    - Unit

after_test:
  - ps: .\.nuget\pack.ps1

artifacts:
  - path: DigiRazor.PasswordService\bin\Release\PasswordValidation.dll
    name: PasswordValidation.dll
  - path: '**\DigiRazor.PasswordValidation*.nupkg'

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: eBMjE7KMZ5PJqLvmGgphxhCgfxwGIFKRb8d8PZvMlvPPAmD0pBUBpw0J//LLUdAJ
#  on:
#    appveyor_repo_tag: true	    
#  artifact: /.*\.nupkg/
