//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiRazor.PasswordValidation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigiRazor.PasswordValidation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCustomValidator Only supports custom validators, for standard validators use SetupRules.
        /// </summary>
        internal static string PasswordService_AddCustomValidatorOnlySupportsCustomValidators {
            get {
                return ResourceManager.GetString("PasswordService_AddCustomValidatorOnlySupportsCustomValidators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password contains black listed words..
        /// </summary>
        internal static string ValidateBlacklist_PasswordContainsBlackListedWords {
            get {
                return ResourceManager.GetString("ValidateBlacklist_PasswordContainsBlackListedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password &amp; Confirm Password must match..
        /// </summary>
        internal static string ValidateConfirmPassword_NewPasswordConfirmPasswordMustMatch {
            get {
                return ResourceManager.GetString("ValidateConfirmPassword_NewPasswordConfirmPasswordMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password may not be any of your previous {0} passwords..
        /// </summary>
        internal static string ValidateHistory_PasswordMayNotBeAnyOfYourPrevious0Passwords {
            get {
                return ResourceManager.GetString("ValidateHistory_PasswordMayNotBeAnyOfYourPrevious0Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {0} characters long..
        /// </summary>
        internal static string ValidateLength_PasswordMustBeAtLeast0CharactersLong {
            get {
                return ResourceManager.GetString("ValidateLength_PasswordMustBeAtLeast0CharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between {0} and {1} characters long..
        /// </summary>
        internal static string ValidateLength_PasswordMustBeBetween0And1CharactersLong {
            get {
                return ResourceManager.GetString("ValidateLength_PasswordMustBeBetween0And1CharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 1 Lowercase character..
        /// </summary>
        internal static string ValidateLowercase_PasswordMustContainAtLeast1LowercaseCharacter {
            get {
                return ResourceManager.GetString("ValidateLowercase_PasswordMustContainAtLeast1LowercaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 1 Numeric character..
        /// </summary>
        internal static string ValidateNumeric_PasswordMustContainAtLeast1NumericCharacter {
            get {
                return ResourceManager.GetString("ValidateNumeric_PasswordMustContainAtLeast1NumericCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 1 of the following characters: {0}.
        /// </summary>
        internal static string ValidateSpecial_PasswordMustContainAtLeast1OfTheFollowingCharacters {
            get {
                return ResourceManager.GetString("ValidateSpecial_PasswordMustContainAtLeast1OfTheFollowingCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 1 Uppercase character..
        /// </summary>
        internal static string ValidateUppercase_PasswordMustContainAtLeast1UppercaseCharacter {
            get {
                return ResourceManager.GetString("ValidateUppercase_PasswordMustContainAtLeast1UppercaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password may not contain the UserId/ User name..
        /// </summary>
        internal static string ValidateUserId_PasswordMayNotContainTheUserIdUserName {
            get {
                return ResourceManager.GetString("ValidateUserId_PasswordMayNotContainTheUserIdUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password may not contain a space..
        /// </summary>
        internal static string ValidateWhiteSpace_PasswordMayNotContainASpace {
            get {
                return ResourceManager.GetString("ValidateWhiteSpace_PasswordMayNotContainASpace", resourceCulture);
            }
        }
    }
}
